steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/focal-dolphin-447218-v5/jainajani1-100996578/app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/focal-dolphin-447218-v5/jainajani1-100996578/app:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy assignment2-service \
      --image=us-central1-docker.pkg.dev/focal-dolphin-447218-v5/jainajani1-100996578/app:$COMMIT_SHA \
      --region=us-central1 \
      --platform=managed \
      --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
